# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200106_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 6, 23, 5, 44, 786371), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 6, 23, 5, 44, 788369), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='videoblog',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 6, 23, 5, 44, 789368), verbose_name='Дата'),
        ),
    ]
