# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-07 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200107_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 7, 15, 4, 34, 909034), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 7, 15, 4, 34, 910033), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='videoblog',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 7, 15, 4, 34, 911033), verbose_name='Дата'),
        ),
    ]
