# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-08 12:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200107_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 8, 15, 51, 49, 24955), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 8, 15, 51, 49, 26953), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2020, 1, 8, 15, 51, 49, 27954), verbose_name='Дата'),
        ),
    ]
